"""A python client library for Google Weather API."""

from .api import GoogleWeatherApi
from .exceptions import (
    GoogleWeatherApiAuthError,
    GoogleWeatherApiConnectionError,
    GoogleWeatherApiError,
    GoogleWeatherApiResponseError,
)
from .model import (
    AirPressure,
    CurrentConditionsHistory,
    CurrentConditionsResponse,
    DailyForecastResponse,
    Date,
    DateTime,
    ForecastDay,
    ForecastDayPart,
    ForecastHour,
    HourlyForecastResponse,
    IceThickness,
    Interval,
    LocalizedText,
    MinuteForecastResponse,
    MoonEvents,
    Precipitation,
    PrecipitationProbability,
    PrecipitationSegment,
    QuantitativePrecipitationForecast,
    SunEvents,
    Temperature,
    TimeZone,
    Visibility,
    WeatherCondition,
    Wind,
    WindDirection,
    WindSpeed,
)

__all__ = [
    "AirPressure",
    "CurrentConditionsHistory",
    "CurrentConditionsResponse",
    "DailyForecastResponse",
    "Date",
    "DateTime",
    "ForecastDay",
    "ForecastDayPart",
    "ForecastHour",
    "GoogleWeatherApi",
    "GoogleWeatherApiAuthError",
    "GoogleWeatherApiConnectionError",
    "GoogleWeatherApiError",
    "GoogleWeatherApiResponseError",
    "HourlyForecastResponse",
    "IceThickness",
    "Interval",
    "LocalizedText",
    "MinuteForecastResponse",
    "MoonEvents",
    "Precipitation",
    "PrecipitationProbability",
    "PrecipitationSegment",
    "QuantitativePrecipitationForecast",
    "SunEvents",
    "Temperature",
    "TimeZone",
    "Visibility",
    "WeatherCondition",
    "Wind",
    "WindDirection",
    "WindSpeed",
]
